export { default as AccomsPage } from "./accomsPage/AccomsPage";
export { default as AdminPage } from "./adminPage/AdminPage";
export { default as LandlordHome } from "./landlordHome/LandlordHome";
export { default as LandlordProfile } from "./landlord_profile/LandlordProfile";
export { default as Listing } from "./listing/Listing";
export { default as UserProfile } from "./userProfile/UserProfile";
export { default as Home } from "./home/Home";
export { default as Details } from "./detailsPage/details";
export { default as DevPage } from "./devPage/DevPage";
export { default as NotFound } from "./notFound/NotFound"
